# History-rung benchmark: linear, random forest, XGBoost, LightGBM and ANN

Every family is fitted on the same rows, folds and rungs of `12_History_Features`, with the target `y = PL - a` (deviation from the
link's previous-hour mean). Protocol:

* Rungs: every family is fitted on all seven rungs, H1 (link history), H2 (+ same-channel history), H3 (+ clock), H4 (+ SF), H5 (+ earlier SNR),
  H6 (+ the five sensors) and H7 (+ link level and geometry).
* Hyperparameters: one Bayesian search per family on rung H4, 20 candidates, scored on the five expanding-window folds of a one-in-ten
  row sample (every tenth row, folds kept), then the chosen configuration is refitted on the full rows at every rung. The static
  notebooks searched 60 candidates on all rows; here the searches are lighter because every family is fitted seven times more.
* Predictions: out-of-fold for folds 0-4 (fold k trained on everything before it) and hold-out from the model fitted on all training rows.
* ANN: the same multilayer perceptron as `07_ANN` (Adam, early stopping on the last 10 % of the training rows in time order), averaged over
  three seeds instead of thirty.
* Fade margin: the empirical quantile of the out-of-fold residuals (`margin_tools.shift_pooled`, the split-conformal shift used in every notebook that calibrates a margin), checked on the hold-out.
* Unseen link at H4: fit on five links with folds below 4, calibrate the margin on their fold 4, test on the sixth link's hold-out. The reference with the link in training is the same model fitted on folds below 4 of all six links and calibrated on their fold 4, so that the two differ only by the presence of the link.

Residual files are written as `Residuals/residuals_<family>_<rung>_oof.csv` and `_test.csv` in the schema of the static notebooks.
kNN runs in `14_History_kNN` (GPU kernel); `15_Information_by_Family` collects everything.

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"       # XGBoost on the GPU; the ANN is small and stays on the CPU (see below)
import json
import time
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from skopt import BayesSearchCV
from skopt.space import Real, Integer
import xgboost as xgb
import lightgbm as lgb
from margin_tools import shift_pooled

RANDOM_STATE = 42
N_JOBS = 32
TARGETS = (0.90, 0.95, 0.99)

In [2]:
train = pd.read_csv("Data_Files/history_train.csv")
test = pd.read_csv("Data_Files/history_test.csv")
rungs = json.load(open("Data_Files/history_rungs.json"))
d = pd.concat([train, test], ignore_index=True)
d["t"] = pd.to_datetime(d["t"], utc=True)
d = d.sort_values("t").reset_index(drop=True)                 # time order: the ANN takes its early-stopping set from the end, residual files feed the block bootstrap
fold = d["fold"].to_numpy()
H = {k.split()[0]: v for k, v in rungs.items()}            # "H1" ... "H7"

# the same rows for every family and rung: an anchor and a complete H7 input
ok = (d["y"].notna() & d[H["H7"]].notna().all(axis=1)).to_numpy()
is_test = fold == 9
cal = ok & (fold >= 0) & (fold < 9)                         # validation folds 0-4: calibration rows
ev = ok & is_test                                           # hold-out rows
PL, a, y = d["PL"].to_numpy(), d["a"].to_numpy(), d["y"].to_numpy()
X_all = d[H["H7"]].copy()
X_all = X_all.fillna(X_all[ok & (fold < 9)].median())      # no missing values reach the models
print(f"rows: training {int((ok & (fold < 9)).sum()):,} | calibration (folds 0-4) {int(cal.sum()):,} | hold-out {int(ev.sum()):,} of {int(is_test.sum()):,}")

rows: training 2,126,679 | calibration (folds 0-4) 1,773,285 | hold-out 531,983 of 532,055

In [3]:
def rmse(e):
    return float(np.sqrt(np.mean(np.square(e))))

def margins(e_cal, e_test):
    """The margin at each target: the empirical quantile of the calibration residuals (the split-conformal shift of margin_tools), and the share of hold-out residuals it covers."""
    out = {}
    for rho in TARGETS:
        fm = shift_pooled(e_cal, rho)
        out[f"margin {rho:.2f}"], out[f"reached {rho:.2f}"] = fm, float((e_test <= fm).mean())
    return out

def oof_and_test(make, cols):
    """Out-of-fold predictions of y for folds 0-4 and hold-out predictions from the model fitted on all training rows."""
    X = X_all[cols].to_numpy()
    p = np.full(len(d), np.nan)
    for k in range(5):
        tr, va = ok & (fold < k), ok & (fold == k)
        p[va] = make().fit(X[tr], y[tr]).predict(X[va])
    tr = ok & (fold < 9)
    model = make().fit(X[tr], y[tr])
    p[ev] = model.predict(X[ev])
    return p, model

def save_residuals(name, p):
    for split, mask in (("oof", cal), ("test", ev)):
        pd.DataFrame({"model": name, "split": split, "row_id": np.flatnonzero(mask), "fold": fold[mask], "time": d["t"].to_numpy()[mask],
                      "device_id": d["device_id"].to_numpy()[mask], "PL_true": PL[mask], "PL_pred": (a + p)[mask], "resid_db": (y - p)[mask]}
                     ).to_csv(f"Residuals/residuals_{name}_{split}.csv", index=False)

def evaluate(name, p):
    e = y - p
    row = {"hold-out RMSE": rmse(e[ev]), "hold-out MAE": float(np.abs(e[ev]).mean()), "OOF RMSE": rmse(e[cal])}
    row.update(margins(e[cal], e[ev]))
    return row

os.makedirs("Residuals", exist_ok=True)
os.makedirs("CV_Results", exist_ok=True)
results = {}

In [4]:
# References that need no model: the per-link training mean (the static floor) and the anchor itself
for name, p in (("link mean", d["devmean"].to_numpy() - a), ("previous-hour mean", np.zeros(len(d))), ("previous packet", d["r_lag1"].to_numpy())):
    results[(name, "-")] = evaluate(name, p)
pd.DataFrame(results).T.round(3)

,,hold-out RMSE,hold-out MAE,OOF RMSE,margin 0.90,reached 0.90,margin 0.95,reached 0.95,margin 0.99,reached 0.99
link mean,-,4.943,3.942,6.031,7.376,0.965,10.815,0.985,18.785,0.998
previous-hour mean,-,2.481,1.837,3.289,3.418,0.917,4.837,0.970,10.618,0.999
previous packet,-,2.962,2.179,4.283,4.000,0.941,6.000,0.986,12.000,0.999

In [5]:
# One light Bayesian search per family on rung H4, every tenth row, folds kept
sub = np.flatnonzero(ok & (fold < 9))[::10]
X_sub, y_sub, fold_sub = X_all[H["H4"]].to_numpy()[sub], y[sub], fold[sub]
cv_sub = [(np.flatnonzero(fold_sub < k), np.flatnonzero(fold_sub == k)) for k in range(5)]

def search(name, estimator, space, n_jobs):
    t0 = time.time()
    bs = BayesSearchCV(estimator, space, n_iter=20, cv=cv_sub, scoring="neg_root_mean_squared_error", n_jobs=n_jobs, n_points=2,
                       random_state=RANDOM_STATE, refit=False)
    bs.fit(X_sub, y_sub)
    pd.DataFrame(bs.cv_results_).to_csv(f"CV_Results/history_{name}_search.csv", index=False)
    print(f"{name}: best CV RMSE {-bs.best_score_:.3f} dB on the sample after {time.time() - t0:.0f} s -> {bs.best_params_}")
    return dict(bs.best_params_)

best = {}
best["RF"] = search("RF", RandomForestRegressor(n_estimators=300, random_state=RANDOM_STATE, n_jobs=4),
                    {"max_depth": Integer(4, 32), "min_samples_leaf": Integer(5, 500), "max_features": Real(0.3, 0.9), "max_samples": Real(0.5, 1.0)}, n_jobs=8)
best["XGB"] = search("XGB", xgb.XGBRegressor(device="cuda", tree_method="hist", random_state=RANDOM_STATE, n_jobs=1),
                     {"max_depth": Integer(3, 10), "learning_rate": Real(0.01, 0.2, prior="log-uniform"), "n_estimators": Integer(200, 1500),
                      "min_child_weight": Real(1, 2000, prior="log-uniform"), "subsample": Real(0.6, 1.0), "colsample_bytree": Real(0.5, 1.0),
                      "reg_lambda": Real(0.1, 30, prior="log-uniform")}, n_jobs=1)
best["LGBM"] = search("LGBM", lgb.LGBMRegressor(subsample_freq=1, random_state=RANDOM_STATE, n_jobs=4, verbose=-1),
                      {"num_leaves": Integer(15, 255), "learning_rate": Real(0.01, 0.2, prior="log-uniform"), "n_estimators": Integer(200, 1500),
                       "min_child_samples": Integer(20, 1000), "subsample": Real(0.6, 1.0), "colsample_bytree": Real(0.5, 1.0),
                       "reg_lambda": Real(0.1, 30, prior="log-uniform")}, n_jobs=8)
json.dump(best, open("CV_Results/history_best_params.json", "w"), indent=1, default=float)

RF: best CV RMSE 2.629 dB on the sample after 914 s -> OrderedDict({'max_depth': 17, 'max_features': 0.7131535881047624, 'max_samples': 1.0, 'min_samples_leaf': 75})

/home/nahshon/envs/ml001/lib/python3.12/site-packages/xgboost/core.py:158: UserWarning: [18:39:46] WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  warnings.warn(smsg, UserWarning)

XGB: best CV RMSE 2.568 dB on the sample after 636 s -> OrderedDict({'colsample_bytree': 0.8697521170952103, 'learning_rate': 0.024895216086676577, 'max_depth': 8, 'min_child_weight': 65.38038421751166, 'n_estimators': 365, 'reg_lambda': 0.2761439033398466, 'subsample': 0.8528382512601542})

LGBM: best CV RMSE 2.568 dB on the sample after 198 s -> OrderedDict({'colsample_bytree': 0.9061979941786817, 'learning_rate': 0.0167343965754388, 'min_child_samples': 606, 'n_estimators': 1244, 'num_leaves': 141, 'reg_lambda': 0.17236683473219908, 'subsample': 0.9023202131343526})

In [6]:
# Linear, RF, XGBoost and LightGBM on the seven rungs
class Linear:
    def __init__(self):
        self.scaler, self.model = StandardScaler(), Ridge(alpha=1.0)
    def fit(self, X, y):
        self.model.fit(self.scaler.fit_transform(X), y)
        return self
    def predict(self, X):
        return self.model.predict(self.scaler.transform(X))

factories = {
    "Linear": lambda: Linear(),
    "RF": lambda: RandomForestRegressor(n_estimators=300, random_state=RANDOM_STATE, n_jobs=N_JOBS, **best["RF"]),
    "XGB": lambda: xgb.XGBRegressor(device="cuda", tree_method="hist", random_state=RANDOM_STATE, **best["XGB"]),
    "LGBM": lambda: lgb.LGBMRegressor(subsample_freq=1, random_state=RANDOM_STATE, n_jobs=8, verbose=-1, **best["LGBM"]),   # 8 threads: LightGBM stalls when oversubscribed
}
for name, make in factories.items():
    for rung in H:
        t0 = time.time()
        p, _ = oof_and_test(make, H[rung])
        results[(name, rung)] = evaluate(name, p)
        save_residuals(f"{name}_{rung}", p)
        print(f"{name} {rung}: hold-out RMSE {results[(name, rung)]['hold-out RMSE']:.3f} dB, margin 0.99 {results[(name, rung)]['margin 0.99']:.2f} dB  ({time.time() - t0:.0f} s)")

Linear H1: hold-out RMSE 2.323 dB, margin 0.99 9.78 dB  (18 s)

Linear H2: hold-out RMSE 2.195 dB, margin 0.99 9.60 dB  (19 s)

Linear H3: hold-out RMSE 2.195 dB, margin 0.99 9.59 dB  (20 s)

Linear H4: hold-out RMSE 2.187 dB, margin 0.99 9.70 dB  (19 s)

Linear H5: hold-out RMSE 2.185 dB, margin 0.99 9.72 dB  (20 s)

Linear H6: hold-out RMSE 2.185 dB, margin 0.99 9.71 dB  (21 s)

Linear H7: hold-out RMSE 2.185 dB, margin 0.99 9.72 dB  (21 s)

RF H1: hold-out RMSE 2.175 dB, margin 0.99 9.01 dB  (1153 s)

RF H2: hold-out RMSE 2.027 dB, margin 0.99 8.91 dB  (1327 s)

RF H3: hold-out RMSE 2.027 dB, margin 0.99 8.90 dB  (1298 s)

RF H4: hold-out RMSE 1.797 dB, margin 0.99 8.04 dB  (1516 s)

RF H5: hold-out RMSE 1.796 dB, margin 0.99 8.05 dB  (1544 s)

RF H6: hold-out RMSE 1.796 dB, margin 0.99 8.05 dB  (1810 s)

RF H7: hold-out RMSE 1.796 dB, margin 0.99 8.02 dB  (1886 s)

XGB H1: hold-out RMSE 2.180 dB, margin 0.99 8.99 dB  (239 s)

XGB H2: hold-out RMSE 1.956 dB, margin 0.99 8.62 dB  (125 s)

XGB H3: hold-out RMSE 1.960 dB, margin 0.99 8.62 dB  (241 s)

XGB H4: hold-out RMSE 1.774 dB, margin 0.99 7.87 dB  (163 s)

XGB H5: hold-out RMSE 1.773 dB, margin 0.99 7.88 dB  (248 s)

XGB H6: hold-out RMSE 1.774 dB, margin 0.99 7.89 dB  (249 s)

XGB H7: hold-out RMSE 1.773 dB, margin 0.99 7.85 dB  (209 s)

LGBM H1: hold-out RMSE 2.159 dB, margin 0.99 8.91 dB  (166 s)

LGBM H2: hold-out RMSE 1.894 dB, margin 0.99 8.33 dB  (245 s)

LGBM H3: hold-out RMSE 1.892 dB, margin 0.99 8.34 dB  (228 s)

LGBM H4: hold-out RMSE 1.770 dB, margin 0.99 7.73 dB  (205 s)

LGBM H5: hold-out RMSE 1.765 dB, margin 0.99 7.72 dB  (241 s)

LGBM H6: hold-out RMSE 1.767 dB, margin 0.99 7.76 dB  (281 s)

LGBM H7: hold-out RMSE 1.767 dB, margin 0.99 7.72 dB  (330 s)

In [7]:
# ANN: the multilayer perceptron of 07_ANN, three seeds averaged, early stopping on the last 10 % of the training rows in time order
import tensorflow as tf
from tensorflow import keras
tf.config.set_visible_devices([], "GPU")                    # small network: the CPU is faster than the GPU transfer, and the GPU is XGBoost's

ANN_SEEDS = (0, 1, 2)

def ann_candidates():
    return {(32, 16): None, (64, 32): None, (64, 32, 16): None, (128, 64, 32): None}

class ANN:
    def __init__(self, layers, seeds=ANN_SEEDS):
        self.layers, self.seeds, self.scaler, self.nets = layers, seeds, StandardScaler(), []
    def fit(self, X, y):
        Xs = self.scaler.fit_transform(X).astype(np.float32); y = y.astype(np.float32)
        n_val = max(1, len(Xs) // 10)                             # the last tenth in time order is the early-stopping set
        self.nets = []
        for seed in self.seeds:
            tf.keras.utils.set_random_seed(seed)
            net = keras.Sequential([keras.Input(shape=(Xs.shape[1],))] + [keras.layers.Dense(n, activation="relu") for n in self.layers] + [keras.layers.Dense(1)])
            net.compile(optimizer=keras.optimizers.Adam(1e-3), loss="mse")
            net.fit(Xs[:-n_val], y[:-n_val], validation_data=(Xs[-n_val:], y[-n_val:]), epochs=200, batch_size=2048, verbose=0,
                    callbacks=[keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True),
                               keras.callbacks.ReduceLROnPlateau(factor=0.5, patience=4, min_lr=1e-5)])
            self.nets.append(net)
        return self
    def predict(self, X):
        Xs = self.scaler.transform(X).astype(np.float32)
        return np.mean([net.predict(Xs, batch_size=8192, verbose=0).ravel() for net in self.nets], axis=0)

# architecture screen on the sample (one seed), scored on its five folds
screen = {}
for layers in ann_candidates():
    scores = []
    for tr, va in cv_sub:
        m = ANN(layers, seeds=(0,)).fit(X_sub[tr], y_sub[tr])
        scores.append(rmse(y_sub[va] - m.predict(X_sub[va])))
    screen[layers] = float(np.mean(scores))
    print(f"ANN {layers}: sample CV RMSE {screen[layers]:.3f} dB")
best["ANN"] = min(screen, key=screen.get)
json.dump({k: (list(v) if k == "ANN" else v) for k, v in best.items()}, open("CV_Results/history_best_params.json", "w"), indent=1, default=float)
print("selected ANN architecture:", best["ANN"])

for rung in H:
    t0 = time.time()
    p, _ = oof_and_test(lambda: ANN(best["ANN"]), H[rung])
    results[("ANN", rung)] = evaluate("ANN", p)
    save_residuals(f"ANN_{rung}", p)
    print(f"ANN {rung}: hold-out RMSE {results[('ANN', rung)]['hold-out RMSE']:.3f} dB, margin 0.99 {results[('ANN', rung)]['margin 0.99']:.2f} dB  ({time.time() - t0:.0f} s)")

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1792615445.145976 1616642 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1792615445.174349 1616642 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1792615446.292812 1616642 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

W0000 00:00:1792615447.308740 1616642 gpu_device.cc:2459] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0a. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.

I0000 00:00:1792615447.870336 1749919 service.cc:153] XLA service 0x73c9d0019070 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1792615447.870350 1749919 service.cc:161]   StreamExecutor [0]: Host, Default Version (Driver: 0.0.0; Runtime: 0.0.0; Toolkit: 0.0.0; DNN: 0.0.0)
I0000 00:00:1792615447.891411 1749919 dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.

I0000 00:00:1792615448.128281 1749919 device_compiler.h:208] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

WARNING:tensorflow:5 out of the last 11 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x73cef007f600> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:5 out of the last 11 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x73cef007f600> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

ANN (32, 16): sample CV RMSE 2.775 dB

ANN (64, 32): sample CV RMSE 2.747 dB

ANN (64, 32, 16): sample CV RMSE 2.709 dB

ANN (128, 64, 32): sample CV RMSE 2.757 dB
selected ANN architecture: (64, 32, 16)

ANN H1: hold-out RMSE 2.316 dB, margin 0.99 9.23 dB  (660 s)

ANN H2: hold-out RMSE 2.133 dB, margin 0.99 9.00 dB  (619 s)

ANN H3: hold-out RMSE 2.123 dB, margin 0.99 8.99 dB  (762 s)

ANN H4: hold-out RMSE 1.841 dB, margin 0.99 7.76 dB  (592 s)

ANN H5: hold-out RMSE 1.814 dB, margin 0.99 7.75 dB  (775 s)

ANN H6: hold-out RMSE 1.819 dB, margin 0.99 7.81 dB  (611 s)

ANN H7: hold-out RMSE 1.823 dB, margin 0.99 7.80 dB  (857 s)

In [8]:
# Family table on the seven rungs
table = pd.DataFrame(results).T
table.index.names = ["family", "rung"]
table.to_csv("CV_Results/history_benchmark.csv")
print("hold-out RMSE (dB) by family and rung")
print(table["hold-out RMSE"].unstack("rung").round(3).to_string())
print("\nfade margin for 99 % (dB), calibrated on folds 0-4")
print(table["margin 0.99"].unstack("rung").round(2).to_string())
print("\nreliability reached on the hold-out with that margin")
print(table["reached 0.99"].unstack("rung").round(4).to_string())

hold-out RMSE (dB) by family and rung
rung                    -     H1     H2     H3     H4     H5     H6     H7
family
ANN                   NaN  2.316  2.133  2.123  1.841  1.814  1.819  1.823
LGBM                  NaN  2.159  1.894  1.892  1.770  1.765  1.767  1.767
Linear                NaN  2.323  2.195  2.195  2.187  2.185  2.185  2.185
RF                    NaN  2.175  2.027  2.027  1.797  1.796  1.796  1.796
XGB                   NaN  2.180  1.956  1.960  1.774  1.773  1.774  1.773
link mean           4.943    NaN    NaN    NaN    NaN    NaN    NaN    NaN
previous packet     2.962    NaN    NaN    NaN    NaN    NaN    NaN    NaN
previous-hour mean  2.481    NaN    NaN    NaN    NaN    NaN    NaN    NaN

fade margin for 99 % (dB), calibrated on folds 0-4
rung                    -    H1    H2    H3    H4    H5    H6    H7
family
ANN                   NaN  9.23  9.00  8.99  7.76  7.75  7.81  7.80
LGBM                  NaN  8.91  8.33  8.34  7.73  7.72  7.76  7.72
Linear                NaN  9.78  9.60  9.59  9.70  9.72  9.71  9.72
RF                    NaN  9.01  8.91  8.90  8.04  8.05  8.05  8.02
XGB                   NaN  8.99  8.62  8.62  7.87  7.88  7.89  7.85
link mean           18.79   NaN   NaN   NaN   NaN   NaN   NaN   NaN
previous packet     12.00   NaN   NaN   NaN   NaN   NaN   NaN   NaN
previous-hour mean  10.62   NaN   NaN   NaN   NaN   NaN   NaN   NaN

reliability reached on the hold-out with that margin
rung                     -      H1      H2      H3      H4      H5      H6      H7
family
ANN                    NaN  0.9988  0.9989  0.9989  0.9986  0.9986  0.9986  0.9986
LGBM                   NaN  0.9987  0.9986  0.9986  0.9985  0.9985  0.9985  0.9985
Linear                 NaN  0.9988  0.9988  0.9988  0.9989  0.9989  0.9989  0.9989
RF                     NaN  0.9987  0.9988  0.9988  0.9986  0.9986  0.9986  0.9986
XGB                    NaN  0.9987  0.9987  0.9987  0.9986  0.9986  0.9986  0.9986
link mean           0.9979     NaN     NaN     NaN     NaN     NaN     NaN     NaN
previous packet     0.9992     NaN     NaN     NaN     NaN     NaN     NaN     NaN
previous-hour mean  0.9987     NaN     NaN     NaN     NaN     NaN     NaN     NaN

In [9]:
# A link the model has never seen (rung H4): fit on five links with folds below 4, calibrate on their fold 4, test on the sixth link's hold-out.
# The reference with the link in training uses the same blocks: one fit per family on folds below 4 of all six links, calibrated on their fold 4,
# so that the two differ only by the presence of the link
dev = d["device_id"].to_numpy()
X4 = X_all[H["H4"]].to_numpy()
links = sorted(np.unique(dev))
fit_all, cal_all = ok & (fold >= 0) & (fold < 4), cal & (fold == 4)
unseen = {}
for name, make in {**factories, "ANN": lambda: ANN(best["ANN"])}.items():
    m_all = make().fit(X4[fit_all], y[fit_all])
    fm_all = shift_pooled(y[cal_all] - m_all.predict(X4[cal_all]), 0.99)
    for link in links:
        other, this = dev != link, dev == link
        fit_m, cal_m, test_m = ok & other & (fold >= 0) & (fold < 4), cal & other & (fold == 4), ev & this
        m = make().fit(X4[fit_m], y[fit_m])
        e_cal, e_test, e_in = y[cal_m] - m.predict(X4[cal_m]), y[test_m] - m.predict(X4[test_m]), y[test_m] - m_all.predict(X4[test_m])
        fm = shift_pooled(e_cal, 0.99)
        unseen[(name, link)] = {"RMSE on the unseen link": rmse(e_test), "margin 0.99 from five links": fm, "reached on the unseen link": float((e_test <= fm).mean()),
                                "RMSE with the link in training": rmse(e_in), "margin 0.99 from six links": fm_all, "reached with the link in training": float((e_in <= fm_all).mean())}
unseen_df = pd.DataFrame(unseen).T
unseen_df.index.names = ["family", "link"]
unseen_df.to_csv("CV_Results/history_unseen_link.csv")
print("RMSE on the unseen link (dB)")
print(unseen_df["RMSE on the unseen link"].unstack("link").round(2).to_string())
print("\nRMSE with the link in training on the same blocks (dB)")
print(unseen_df["RMSE with the link in training"].unstack("link").round(2).to_string())
print("\ntransfer penalty, unseen minus with the link in training (dB)")
print((unseen_df["RMSE on the unseen link"] - unseen_df["RMSE with the link in training"]).unstack("link").round(2).to_string())
print("\nreliability reached on the unseen link with the 99 % margin calibrated on the other five")
print(unseen_df["reached on the unseen link"].unstack("link").round(4).to_string())

RMSE on the unseen link (dB)
link     ED0   ED1   ED2   ED3   ED4   ED5
family
ANN     1.80  2.00  2.02  1.72  1.84  1.82
LGBM    1.79  1.99  2.02  1.70  1.79  1.77
Linear  2.19  2.32  2.37  2.02  2.12  2.13
RF      1.81  2.00  2.05  1.71  1.82  1.79
XGB     1.78  1.98  2.01  1.69  1.79  1.77

RMSE with the link in training on the same blocks (dB)
link     ED0   ED1   ED2   ED3   ED4   ED5
family
ANN     1.78  2.01  2.01  1.70  1.80  1.78
LGBM    1.79  1.99  2.01  1.69  1.79  1.76
Linear  2.19  2.31  2.37  2.01  2.12  2.12
RF      1.81  2.00  2.04  1.70  1.82  1.79
XGB     1.78  1.97  2.01  1.67  1.78  1.76

transfer penalty, unseen minus with the link in training (dB)
link     ED0   ED1   ED2   ED3   ED4   ED5
family
ANN     0.02 -0.01  0.00  0.02  0.04  0.04
LGBM   -0.00  0.01  0.01  0.01 -0.00  0.01
Linear -0.00  0.00  0.00  0.01 -0.00  0.01
RF      0.00 -0.00  0.01  0.01 -0.00  0.01
XGB     0.01  0.02  0.01  0.02  0.01  0.02

reliability reached on the unseen link with the 99 % margin calibrated on the other five
link       ED0     ED1     ED2     ED3     ED4     ED5
family
ANN     0.9978  0.9983  0.9944  0.9995  0.9978  0.9975
LGBM    0.9971  0.9982  0.9935  0.9993  0.9976  0.9973
Linear  0.9976  0.9982  0.9947  0.9993  0.9981  0.9983
RF      0.9975  0.9981  0.9937  0.9993  0.9975  0.9974
XGB     0.9975  0.9983  0.9939  0.9994  0.9977  0.9975

In [10]:
# Per-link hold-out RMSE at H4
per_link = {}
for name in list(factories) + ["ANN"]:
    r = pd.read_csv(f"Residuals/residuals_{name}_H4_test.csv", usecols=["device_id", "resid_db"])
    per_link[name] = r.groupby("device_id")["resid_db"].apply(lambda s: float(np.sqrt(np.mean(np.square(s)))))
per_link = pd.DataFrame(per_link)
per_link["previous-hour mean"] = pd.Series(y[ev]).groupby(dev[ev]).apply(lambda s: float(np.sqrt(np.mean(np.square(s)))))
per_link.round(3)

           Linear     RF    XGB   LGBM    ANN  previous-hour mean
device_id
ED0         2.187  1.746  1.727  1.726  1.776               2.464
ED1         2.312  1.948  1.923  1.923  1.985               2.483
ED2         2.365  1.971  1.944  1.934  2.007               2.783
ED3         2.006  1.621  1.612  1.610  1.689               2.168
ED4         2.119  1.745  1.715  1.708  1.798               2.437
ED5         2.111  1.721  1.697  1.690  1.768               2.505